# TODO: pin versions of images
version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - db

volumes:
  postgres_data_prod:
  redis_data_prod:
