version: '3'
services:
  # TODO: pin versions of images
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
